<?php

include './inc/head.php';
include './inc/const.php';
include './inc/db.php';

$programs=[
    [
        "id"=> "1",
        "name"=> "Tarteel",
        "category"=> "minor",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "2",
        "name"=> "Elocution Malayalam",
        "category"=> "minor",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "3",
        "name"=> "Elocution English",
        "category"=> "minor",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "4",
        "name"=> "Talk Master Arabic",
        "category"=> "minor",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "2",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "5",
        "name"=> "Group Song",
        "category"=> "minor",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "4",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "6",
        "name"=> "Madh Song",
        "category"=> "minor",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "7",
        "name"=> "Quiz",
        "category"=> "minor",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "8",
        "name"=> "Swarf Test",
        "category"=> "minor",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "9",
        "name"=> "Word Game Arabic (Padhakkalari)",
        "category"=> "minor",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "10",
        "name"=> "Ibarath Reading",
        "category"=> "minor",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "11",
        "name"=> "Essay Malayalam",
        "category"=> "minor",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "12",
        "name"=> "Essay English",
        "category"=> "minor",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> "2"
      ],
      [
        "id"=> "13",
        "name"=> "Story Malayalam",
        "category"=> "minor",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "14",
        "name"=> "Story Arabic",
        "category"=> "minor",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "15",
        "name"=> "Poem Malayalam",
        "category"=> "minor",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "16",
        "name"=> "Pygmy Poem English",
        "category"=> "minor",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "17",
        "name"=> "Book Test",
        "category"=> "minor",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "18",
        "name"=> "Written Translation Eng-Mal",
        "category"=> "minor",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "19",
        "name"=> "Sudoku",
        "category"=> "minor",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "20",
        "name"=> "Watercoloring",
        "category"=> "minor",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "21",
        "name"=> "Imla’",
        "category"=> "minor",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "22",
        "name"=> "Hifzul Qur’an",
        "category"=> "minor",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "23",
        "name"=> "Handwriting English",
        "category"=> "minor",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "ongoing",
        "order"=> "1"
      ],
      [
        "id"=> "24",
        "name"=> "Grammar Mastery",
        "category"=> "minor",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "25",
        "name"=> "Maths Relay",
        "category"=> "minor",
        "isStage"=> "0",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "3",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "26",
        "name"=> "Collage",
        "category"=> "minor",
        "isStage"=> "0",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "3",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "27",
        "name"=> "Tarteel",
        "category"=> "premier",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "28",
        "name"=> "Elocution Malayalam",
        "category"=> "premier",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "29",
        "name"=> "Elocution Arabic",
        "category"=> "premier",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "30",
        "name"=> "Devotional Song",
        "category"=> "premier",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "31",
        "name"=> "Talk Master English",
        "category"=> "premier",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "2",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "32",
        "name"=> "Nasheeda",
        "category"=> "premier",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "5",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "33",
        "name"=> "Paper Presentation English ",
        "category"=> "premier",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "34",
        "name"=> "Quiz",
        "category"=> "premier",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "35",
        "name"=> "Nahv Test",
        "category"=> "premier",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "36",
        "name"=> "Swarf Test",
        "category"=> "premier",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "37",
        "name"=> "Ibarath Reading",
        "category"=> "premier",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "38",
        "name"=> "Essay Malayalam",
        "category"=> "premier",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "39",
        "name"=> "Essay English",
        "category"=> "premier",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "40",
        "name"=> "Story Malayalam",
        "category"=> "premier",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "41",
        "name"=> "Story English",
        "category"=> "premier",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "42",
        "name"=> "Poem Malayalam",
        "category"=> "premier",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "43",
        "name"=> "Poem English",
        "category"=> "premier",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "44",
        "name"=> "Pygmy Poem Urdu",
        "category"=> "premier",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "45",
        "name"=> "Pygmy Poem Arabic",
        "category"=> "premier",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "46",
        "name"=> "Book Test",
        "category"=> "premier",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "47",
        "name"=> "Written Translation Eng-Mal",
        "category"=> "premier",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "48",
        "name"=> "Vocabulary Arabic",
        "category"=> "premier",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "49",
        "name"=> "Watercoloring",
        "category"=> "premier",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "50",
        "name"=> "Cartoon Scape",
        "category"=> "premier",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "51",
        "name"=> "Caption Writing",
        "category"=> "premier",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "52",
        "name"=> "Hifzul Muthoon",
        "category"=> "premier",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "53",
        "name"=> "Imla’",
        "category"=> "premier",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "54",
        "name"=> "Hifzul Qur’an",
        "category"=> "premier",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "55",
        "name"=> "Handwriting English",
        "category"=> "premier",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "56",
        "name"=> "Sudoku",
        "category"=> "premier",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "57",
        "name"=> "Magazine",
        "category"=> "premier",
        "isStage"=> "0",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "3",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "58",
        "name"=> "Tarteel",
        "category"=> "subJunior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "59",
        "name"=> "Public Talk English",
        "category"=> "subJunior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "60",
        "name"=> "Elocution Arabic",
        "category"=> "subJunior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "61",
        "name"=> "Elocution Malayalam",
        "category"=> "subJunior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "62",
        "name"=> "Elocution Urdu",
        "category"=> "subJunior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "63",
        "name"=> "Hamd Urdu",
        "category"=> "subJunior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "64",
        "name"=> "Song Arabic",
        "category"=> "subJunior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "65",
        "name"=> "Na’at",
        "category"=> "subJunior",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "4",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "66",
        "name"=> "Quiz",
        "category"=> "subJunior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "67",
        "name"=> "Swarf Test",
        "category"=> "subJunior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "68",
        "name"=> "Nahv Test",
        "category"=> "subJunior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "69",
        "name"=> "Word Game Arabic (Padhakkalari)",
        "category"=> "subJunior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "70",
        "name"=> "Ibarath Reading",
        "category"=> "subJunior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "71",
        "name"=> "Paper Presentation English",
        "category"=> "subJunior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "72",
        "name"=> "Essay Malayalam",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "73",
        "name"=> "Essay English",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "74",
        "name"=> "Essay Arabic",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "75",
        "name"=> "Essay Urdu",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "76",
        "name"=> "Poem Malayalam",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "77",
        "name"=> "Poem English",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "78",
        "name"=> "Poem Arabic",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "79",
        "name"=> "Poem Urdu",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "80",
        "name"=> " Story Malayalam",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "81",
        "name"=> "Story English",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "82",
        "name"=> "Story Arabic",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "83",
        "name"=> "Story Urdu",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "84",
        "name"=> "Social Tweet Malayalam",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "85",
        "name"=> "Dictionary Making Arb-Eng",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "86",
        "name"=> "Written Translation Mal-Eng",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "87",
        "name"=> "Kithabic Test",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "88",
        "name"=> "Book Test",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "89",
        "name"=> "Hifzul Qur’an",
        "category"=> "subJunior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "90",
        "name"=> "Hifzul Muthoon",
        "category"=> "subJunior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "91",
        "name"=> "Calligraphy",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "92",
        "name"=> "Ad Making",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "93",
        "name"=> "Imla’",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "94",
        "name"=> "Digital News Paper",
        "category"=> "subJunior",
        "isStage"=> "0",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "2",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "95",
        "name"=> "Tarteel",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "96",
        "name"=> "Elocution Malayalam",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "97",
        "name"=> "TED Talk",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "98",
        "name"=> "Jalsa Arabic (Elocution Arb)",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "99",
        "name"=> "Talk Master Urdu (Elocution Urd)",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "2",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "100",
        "name"=> "Va’alu",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "101",
        "name"=> "Arabic Kathaprasangam",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "4",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "102",
        "name"=> "Spoken Translation Mal-Arb",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "103",
        "name"=> "Spoken Translation Mal-Eng",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "104",
        "name"=> "Startup Pitching",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "3",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "105",
        "name"=> "Ghazal",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "106",
        "name"=> "Mappilappattu",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "107",
        "name"=> "Campus Song",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "5",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "108",
        "name"=> "Colloquium",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "109",
        "name"=> "Hadees Musabaqa",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "110",
        "name"=> "Quiz",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "111",
        "name"=> "Alfiya Test",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "112",
        "name"=> "Research Poster Presentation (Paper Presentation)",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "113",
        "name"=> "News Reporting (Reading)",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "114",
        "name"=> "Ibarath Reading",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "115",
        "name"=> "Qur’an Mastery",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "2",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "116",
        "name"=> "Poem Malayalam",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "117",
        "name"=> "Poem English",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "118",
        "name"=> "Poem Arabic",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "119",
        "name"=> "Poem Urdu",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "120",
        "name"=> "Story Malayalam",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "121",
        "name"=> "Story English",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "122",
        "name"=> "Story Arabic",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "123",
        "name"=> "Story Urdu",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "124",
        "name"=> "Essay Malayalam",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "125",
        "name"=> "Essay English",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "126",
        "name"=> "Essay Arabic",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "127",
        "name"=> "Essay Urdu",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "128",
        "name"=> "Feature Writing",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "129",
        "name"=> "Madh Song Writing",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "130",
        "name"=> "Social Tweet English",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "131",
        "name"=> "Philosophical Slice",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "132",
        "name"=> "Risala Creation (Book Writing Arabic)",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "133",
        "name"=> "Abstract Writing English",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "134",
        "name"=> "Balaga Test",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "135",
        "name"=> "Book Criticism",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "136",
        "name"=> "Book Review",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "137",
        "name"=> "Sharhul Muthoon",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "138",
        "name"=> "Hifzul Muthoon",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "139",
        "name"=> "Thadrees",
        "category"=> "junior",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "3",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "140",
        "name"=> "Kithabic Test",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "141",
        "name"=> "Book Test",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "142",
        "name"=> "Talent Test",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "143",
        "name"=> "Fiqh Translation Ara-Eng",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "144",
        "name"=> "Written Translation Arabi Mal-Mal",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "145",
        "name"=> "Written Translation Mal-Urd",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "146",
        "name"=> "Prompt Creation",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "147",
        "name"=> "Digital Drawing",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "148",
        "name"=> "Photography",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "149",
        "name"=> "Reel Creation",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "150",
        "name"=> "Calligraffiti",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "151",
        "name"=> "Project",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "152",
        "name"=> "Documentary Presentation",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "153",
        "name"=> "Shoot Out",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "154",
        "name"=> "Swimming",
        "category"=> "junior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "155",
        "name"=> "Elocution Malayalam",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "156",
        "name"=> "Elocution English",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "157",
        "name"=> "Sharia Talk (Elocution Arabic)",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "158",
        "name"=> "Shairi Kalam (Elocution Urdu)",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "159",
        "name"=> "Kathaprasangam Malayalam",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "4",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "160",
        "name"=> "Lecturing English",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "161",
        "name"=> "Ideal Dialogue",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "162",
        "name"=> "Madh Song",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "163",
        "name"=> "Qaseeda",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "5",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "164",
        "name"=> "Qawwali",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "5",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "165",
        "name"=> "Channel Discussion",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "6",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "166",
        "name"=> "Translation Dialogue",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "5",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "167",
        "name"=> "News Bulletin",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "3",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "168",
        "name"=> "Master Plan",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "3",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "169",
        "name"=> "Translation Mal-Urdu",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "2",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "170",
        "name"=> "Global Dars",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "171",
        "name"=> "Paper Presentation English",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "172",
        "name"=> " Live Podcast",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "3",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "173",
        "name"=> "Spoken Translation Mal-Ara",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "174",
        "name"=> "Spoken Translation Mal-Eng",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "175",
        "name"=> "Quiz",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "176",
        "name"=> "Ibarath Reading",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "177",
        "name"=> "Essay Malayalam",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "178",
        "name"=> "Essay English",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "179",
        "name"=> "Essay Arabic",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "180",
        "name"=> "Essay Urdu",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "181",
        "name"=> "Poem Malayalam",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "182",
        "name"=> "Poem English",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "183",
        "name"=> "Poem Arabic",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "184",
        "name"=> "Poem Urdu",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "185",
        "name"=> "Story Malayalam",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "186",
        "name"=> "Story English",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "187",
        "name"=> "Story Arabic",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "188",
        "name"=> "Story Urdu",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "189",
        "name"=> "Mappilappattu Rachana",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "190",
        "name"=> "Talent Test",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "191",
        "name"=> "Journal Review",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "192",
        "name"=> "SOP Writing",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "193",
        "name"=> "Research Paper English",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "194",
        "name"=> "AI Policy Drafting",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "195",
        "name"=> "Kithabic Research (Risala Creation)",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "196",
        "name"=> "E Poster Design",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "197",
        "name"=> "Philosophical Slice",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "198",
        "name"=> "Book Review",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "199",
        "name"=> "Book Criticism",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "200",
        "name"=> "Balaga Test",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "201",
        "name"=> "Sharh Writing (Sharhul Muthoon)",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "202",
        "name"=> "Written Translation Mal-Urd",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "203",
        "name"=> "Hadith Translation",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "204",
        "name"=> "Mas’ala Solution (Iftha’)",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "205",
        "name"=> "Hifzul Muthoon",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "206",
        "name"=> "Trilingual Typing",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "207",
        "name"=> "Branding",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "3",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "208",
        "name"=> "Architectural Photography",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "209",
        "name"=> "Calligraffiti",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "3",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "210",
        "name"=> "Documentary Presentation",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "211",
        "name"=> "Vlogging ",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "1",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "212",
        "name"=> "Shoot Out",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "1",
        "limit"=> "1",
        "members"=> "7",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "213",
        "name"=> "Swimming",
        "category"=> "senior",
        "isStage"=> "0",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> null
      ],
      [
        "id"=> "214",
        "name"=> "Tarteel",
        "category"=> "senior",
        "isStage"=> "1",
        "isGroup"=> "0",
        "limit"=> "2",
        "members"=> "1",
        "status"=> "pending",
        "order"=> "0"
      ]
  ]
  ;
  foreach($programs as $prgrm){
    $sql = "INSERT INTO `schedule` (`program`) VALUES (?)";
    $stmt = $conn->prepare($sql);
    $stmt->bind_param("i", $prgrm['id']);
    $stmt->execute();
  }